name: navigation_engine_mapbox_example
description: navigation_engine on Mapbox with simulated GPS.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  mapbox_maps_flutter: ^3.0.0
  navigation_engine:
    path: ../../navigation_engine
  navigation_engine_flutter:
    path: ../../navigation_engine_flutter
  navigation_engine_mapbox:
    path: ../

dependency_overrides:
  navigation_engine:
    path: ../../navigation_engine
  navigation_engine_flutter:
    path: ../../navigation_engine_flutter
  navigation_engine_mapbox:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
