name: navigation_engine_example
description: Demo of navigation_engine on flutter_map with simulated GPS.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  navigation_engine:
    path: ../
  navigation_engine_flutter:
    path: ../../navigation_engine_flutter
  navigation_engine_flutter_map:
    path: ../../navigation_engine_flutter_map

dependency_overrides:
  navigation_engine:
    path: ../
  navigation_engine_flutter:
    path: ../../navigation_engine_flutter
  navigation_engine_flutter_map:
    path: ../../navigation_engine_flutter_map

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
